from src.pdf.components import (
    create_section_title,
    create_card,
    create_metric_card,
    create_metric_dashboard,
    create_progress,
    create_tag_grid,
    create_table,
    subsection,
    body,
    bullet,
    space,
)


class MetadataPage:

    def build(self, project):

        story = []


        # ==================================================
        # HEADER
        # ==================================================

        story.append(

            create_section_title(
                "Startup Intelligence Overview"
            )

        )

        story.append(
            space(14)
        )


        roadmap = (
            project.roadmap
            if isinstance(project.roadmap, dict)
            else {}
        )


        judge = (
            project.judge
            if isinstance(project.judge, dict)
            else {}
        )


        score = judge.get(
            "overall_score",
            0
        )


        # ==================================================
        # PROJECT DASHBOARD
        # ==================================================

        dashboard = create_metric_dashboard(

            [

                create_metric_card(
                    "AI Score",
                    f"{score}/100"
                ),


                create_metric_card(
                    "Project ID",
                    str(project.id)
                ),


                create_metric_card(
                    "Status",
                    "Completed"
                ),

            ]

        )


        story.append(
            dashboard
        )

        story.append(
            space(16)
        )


        story.append(

            create_progress(score)

        )


        story.append(
            space(22)
        )



        # ==================================================
        # PROJECT IDENTITY
        # ==================================================

        story.append(

            create_card(

                "Project Identity",

                f"""
                <b>Name:</b> {project.project_title}

                <br/><br/>

                <b>Generated By:</b> HackMind AI Copilot

                <br/><br/>

                <b>AI Workflow:</b>
                Planner → Research → Judge → Pitch Architect

                <br/><br/>

                <b>Idea:</b>

                <br/>

                {project.idea}

                """

            )

        )


        story.append(
            space(20)
        )



        # ==================================================
        # FEATURES
        # ==================================================

        features = roadmap.get(
            "features",
            []
        )


        if features:

            feature_text = "<br/>".join(

                [
                    f"✓ {item}"
                    for item in features
                ]

            )


            story.append(

                create_card(

                    "Core Product Features",

                    feature_text

                )

            )


            story.append(
                space(18)
            )



        # ==================================================
        # TECHNOLOGY STACK
        # ==================================================

        tech = roadmap.get(
            "tech_stack",
            {}
        )


        technologies = []


        if isinstance(tech, dict):

            for value in tech.values():

                if isinstance(value,list):

                    technologies.extend(value)



        if technologies:


            story.append(

                subsection(
                    "Technology Ecosystem"
                )

            )


            story.append(

                create_tag_grid(
                    technologies
                )

            )


            story.append(
                space(20)
            )



        # ==================================================
        # SYSTEM ARCHITECTURE
        # ==================================================

        architecture = roadmap.get(
            "system_architecture",
            ""
        )


        if architecture:


            story.append(

                create_card(

                    "System Architecture",

                    architecture

                )

            )


            story.append(
                space(20)
            )



        # ==================================================
        # DEVELOPMENT ROADMAP
        # ==================================================

        timeline = roadmap.get(
            "development_timeline",
            []
        )


        if timeline:


            story.append(

                subsection(
                    "Development Timeline"
                )

            )


            for phase in timeline:


                title = phase.get(
                    "phase",
                    "Phase"
                )


                tasks = phase.get(
                    "tasks",
                    []
                )


                content = "<br/>".join(

                    [
                        f"• {task}"
                        for task in tasks
                    ]

                )


                story.append(

                    create_card(

                        title,

                        content

                    )

                )


                story.append(
                    space(12)
                )



        # ==================================================
        # TEAM STRUCTURE
        # ==================================================

        roles = roadmap.get(
            "team_roles",
            []
        )


        if roles:


            story.append(

                subsection(
                    "Suggested Team Structure"
                )

            )


            for role in roles:


                role_name = role.get(
                    "role",
                    "Team Member"
                )


                responsibilities = role.get(
                    "responsibilities",
                    ""
                )


                story.append(

                    create_card(

                        role_name,

                        responsibilities

                    )

                )


                story.append(
                    space(12)
                )



        return story



metadata_page = MetadataPage()